### ISSUE TITLE
Consider rewrite?

### ISSUE THREAD

**Issue by martinb3** [nathwill/chef-elasticsearch-ng#2]
Hey there! We're working on a re-write of the current elasticsearch cookbook. A lot of it has been made minimal, and now supports packages as well.

Branch: https://github.com/elastic/cookbook-elasticsearch/tree/next
Issues: https://github.com/elastic/cookbook-elasticsearch/labels/next

I'll understand if you feel that your cookbook has different design goals, but if they overlap, I'd love to collaborate with you.

Cheers!

Martin

**Comment by nathwill** [comment]
Hey Martin!

I have no idea how the notifications for this repo slipped past me, sorry for the delay here.

Yeah, the pre-existing elasticsearch cookbook just seemed to handle things quite differently from how I envisioned them at the time I put this together, enough that a PR would have been too much to ask; If you're now working on a rewrite and open to suggestions, I'd be happy to contribute suggestions and do some coding.

I'll go take a look at the branch you linked and see how it looks; if we end up in a place where your ES cookbook fits our needs a little better, I'd be happy to deprecate this one, which hasn't been around all that long after all.

Cheers!

Nathan

**Comment by nathwill** [comment]
oh, this is delightful :D count me in!

**Comment by martinb3** [comment]
>  If you're now working on a rewrite and open to suggestions, I'd be happy to contribute suggestions and do some coding.

We're definitely up for collaboration -- sounds wonderful. We've already re-written a fair amount of it. We were thinking of doing a release sometime in the next few weeks, just to get something out there. If you have any specific things you'd like to see go into a release, or want to take it for a test drive and see if you find anything that needs fixing, let us know :)

Thanks again for the response!
